<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Fuente y CSS -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="public/css/styles.css">

    <title>TODO PISOS</title>
</head>

<body>

    <!-- HEADER / NAVBAR -->
    <nav>
        <div class="logo">
            <a href="index">
                <img src="public/img/logoTodoPisos.jpg" alt="Logo TODO PISOS">
            </a>
        </div>

        <div>
            <ul class="menu">
                <li><a href="index">Home</a></li>
                <li><a href="lista_pisos">Products</a></li>
                <?php
                if (session_status() == PHP_SESSION_NONE) {
                    session_start();
                }
                if (isset($_SESSION['USER_ID'])) : 
                ?>
                    <li><span class="user-email"><?= htmlspecialchars($_SESSION['USER_EMAIL']) ?></span></li>
                    <li><a href="logout">Logout</a></li>
                <?php else : ?>
                    <li><a href="login">Login</a></li>
                    <li><a href="register">Register</a></li>
                <?php endif; ?>
            </ul>
        </div>
    </nav>


    