<?php require 'app/views/templates/layout/header.phtml' ?>

<?php if ($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>

<div class="login-container">
    <form method="POST" action="verificar-login" class="login-form">
        <h2>Iniciar Sesión</h2>

        <label for="email">Correo electrónico</label>
        <input type="email" name="email" id="email" placeholder="ejemplo@correo.com">

        <label for="password">Contraseña</label>
        <input type="password" name="password" id="password" placeholder="********">

        <button type="submit">Login</button>
    </form>
</div>


<?php require 'app/views/templates/layout/footer.phtml' ?>