<?php require 'app/views/templates/layout/header.phtml' ?>

<?php if (isset($error)): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>

<div class="login-container">
    <form method="POST" action="register-user" class="login-form">
        <h2>Registrarse</h2>

        <label for="email">Correo electrónico</label>
        <input type="email" name="email" id="email" placeholder="ejemplo@correo.com" required>

        <label for="password">Contraseña</label>
        <input type="password" name="password" id="password" placeholder="********" required>
        
        <button type="submit">Crear cuenta</button>
    </form>
</div>

<p class="text-center mt-3">¿Ya tienes una cuenta? <a href="login">Inicia sesión</a></p>

<?php require 'app/views/templates/layout/footer.phtml' ?>
