<?php require 'app/views/templates/layout/header.phtml' ?>

<?php if ($error): ?>
<div class='alert alert-danger' role='alert'>
    <?= $error ?>
</div>
<?php endif ?>


<div>
    <h2> Login </h2>
    <form method="POST">
        <label for="email">hola</label>
        <input type="text" name="email" placeholder="hola" required>
        <input type="password" class="form-control" name="password" required>
        <button class="btn btn-primary">Login</button>
    </form>
</div>







<?php require 'app/views/templates/layout/footer.phtml' ?>