<?php require_once './app/views/templates/layout/header.phtml'; ?>

<div class="container">
    <h1>Lista de Categorías</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Nombre</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($categorias as $categoria) : ?>
                <tr>
                    <td><a href="detalle_categoria/<?= $categoria->id ?>"><?= $categoria->nombre ?></a></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php require_once './app/views/templates/layout/footer.phtml'; ?>
