<?php require 'app/views/templates/layout/header.phtml' ?>

<section class="hero">
        <div class="hero-content">
            <h1>Bienvenido a TODO PISOS</h1>
            <p>Descubre nuestra amplia variedad de pisos de cerámica, mármol, travertino y baldosas para transformar tu hogar o negocio con estilo y calidad.</p>
            <a href="lista_pisos" class="btn">Ver Productos</a>
        </div>
    </section>


<?php require 'app/views/templates/layout/footer.phtml' ?>